### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by amyblais** [NDrive/nagios-mattermost#12]
Thanks for sharing this project! We have earlier added your integration in the Mattermost App Directory.

Would you consider adding a license, such as a MIT or an Apache 2.0 license?

To do so, in GitHub you can click "Create new file" and name a file LICENSE.txt.
This will prompt GitHub to offer a license template.

If you use a license it would make it easy to add your work to other open source projects, and we'd love to include your work in ours.

Thanks kindly for your consideration and let me know if you have any questions!

**Comment by andrefreitas** [comment]
Hello,
I no longer work on the organization that maintains this. Pinging @nunodio and @vitorhugomagalhaes to see if they can make this.

**Comment by nunodio** [comment]
Hi,

A license file has been added to the repository.
The project is now licensed under the terms of the MIT license.

**Comment by andrefreitas** [comment]
@nunodio you rock 💪 

@amyblais can you include this project on Mattermost then?

**Comment by amyblais** [comment]
Thank you all!

Yep, it was actually added to the Apps & Integrations page [here](https://about.mattermost.com/community-applications/) already earlier - I just wanted to confirm that I can also list a license for it, which is now done. Thanks all again!
