### ISSUE TITLE
Script Execution Issues

### ISSUE THREAD

**Issue by henryudha** [NDrive/nagios-mattermost#3]
hi @andrefreitas ,

thanks for your script anyway.

kindly need your suggestion.
im quite struggling with your script.
i try by execute : 

python matternag.py --url http://chat.abc.io/abc/channels/trial- --hostalias server1 --notificationtype Problem --serviceoutput "Service Apache Down!"

the last line output are :
`</div>
    <script>
window.setup_login_page({"TeamDisplayName":"abc","TeamName":"abc","Title":"abc-group Chat Line - Login"});
    </script>
</body>
</html>
`

since our mattermost server are working well, is there anything else i need to do ?
do i need to put my username and password inside the script ?

looking forward for your information.

many thanks

cheers,
henry

**Comment by andrefreitas** [comment]
Hi @henryudha,
You only need to give the URL generated by Mattermost when adding an Incoming Webhook (it's an URL with a token). 

**Let's run a checklist (they work great). Please answer y/n for the following points:**
1. Did you create an Incoming Webhook following the instructions at http://docs.mattermost.com/developer/webhooks-incoming.html#enabling-incoming-webhooks ?
2. Did you tested the generated URL with a token with the following command?
   
   ```
   ./mattermost.py --url [URL]  --hostalias "$HOSTNAME$" --notificationtype "$NOTIFICATIONTYPE$" --servicedesc "$SERVICEDESC$" --servicestate "$SERVICESTATE$" --serviceoutput "$SERVICEOUTPUT$"
   ```

**Comment by henryudha** [comment]
hi @andrefreitas 

thanks for your reply,
1. No. i just create the webhook url.
2. then retry to execute with the webhook url, and its work.

you just awesome mate!

once again thanks for your help and reply

cheers,
henry

**Comment by andrefreitas** [comment]
@henryudha you are welcome, glad to see I could help :)
