### ISSUE TITLE
NDrive/nagios-mattermost  plugin installation on Ubuntu

### ISSUE THREAD

**Issue by ghost** [NDrive/nagios-mattermost#6]
Hi,
I am running Nagios and Mattermost on Ubuntu 14.04 and i am new to Ubuntu. Can you guys please help me to integrate Nagios with MM.?
I am successful on enabling webhook URL in MM. However i am facing difficulties on NDrive/nagios-mattermost  plugin installation with Nagios. So Please provide me the detailed steps on plugin installation.

Appreciate your responses.

Thanks.

**Comment by andrefreitas** [comment]
Hi, Sure, the installation instructions are here: https://github.com/NDrive/nagios-mattermost#nagios-configuration

**Comment by ghost** [comment]
Hi, I am tried it, but no luck. Please find below details..

cbadmin@ubuntu:~$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.


cbadmin@ubuntu:~$ ./mattermost.py
./mattermost.py: line 5: syntax error near unexpected token `newline'
./mattermost.py: line 5:`<!DOCTYPE html>'
cbadmin@ubuntu:~$
cbadmin@ubuntu:~$ ./mattermost.py --help
./mattermost.py: line 5: syntax error near unexpected token `newline'
./mattermost.py: line 5:`<!DOCTYPE html>'

cbadmin@ubuntu:~$ cp /home/cbadmin/mattermost.py /home/cbadmin/nagios/libexec
cp: cannot create regular file ‘/home/cbadmin/nagios/libexec’: No such file or directory**_

Please help..

**Comment by andrefreitas** [comment]
> syntax error near unexpected token newline' ./mattermost.py: line 5:<!DOCTYPE html>'

The contents of mattermost.py have html tags. Please use git, curl or wget to download the file with the right content. 

> cannot create regular file ‘/home/cbadmin/nagios/libexec’: No such file or directory**

The error message message says all.

**Comment by ghost** [comment]
@andrefreitas: Thanks for your help. i done the changes as mentioned in  https://github.com/NDrive/nagios-mattermost#nagios-configuration. 

How to verify the status of the plugin? success or not success?

**Comment by andrefreitas** [comment]
@Mutha2838, Github issues are for discussing bugs and new features. 

If you need IT support, you should hire/outsource someone. The instructions are clear in the Readme. I cannot help you understand how Nagios and Linux work.

Best regards.
